<a href="https://colab.research.google.com/github/ergonrizky26/3-Months-of-Data-Science/blob/main/Day_3_Numpy_and_Inbuilt_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Tutorials

NumPy is a general purpose array-processing package. It provides a high-performance multidimensional array object, and <br>
tools for working with these arrays. It is the fndamental package for scientific computing with Python

# What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and <br>
lists. While Python lists can contain values corresponding to different data types, arrays in Python can only contain values corresponding to same data type

In [1]:
# Initially import numpy

import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]

# Converting list to array
arr = np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
# Multinested array

my_list1 = [1, 2, 3, 4, 5]
my_list2 = [2, 3, 4, 5, 6]
my_list3 = [7, 8, 9, 10, 11]

arr = np.array([my_list1, my_list2, my_list3])

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [10]:
# To check how many rows and column in array
arr.shape

(3, 5)

In [11]:
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Indexing

In [13]:
# Accessing the array elements

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1[3]

4

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [18]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [19]:
arr[1:,3:]

array([[ 5,  6],
       [10, 11]])

In [23]:
arr1 = np.arange(0,10, step=2)

In [24]:
arr1

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [28]:
# Copy() function and broadcasting

arr1[3:] = 100

In [29]:
arr1

array([  0,   2,   4, 100, 100])

In [32]:
arr2 = arr1

In [33]:
arr2[3:] = 500
print(arr2)

[  0   2   4 500 500]


In [34]:
arr1

array([  0,   2,   4, 500, 500])

In [37]:
arr2 = arr1.copy()

In [38]:
print(arr1)
arr2[3:] = 1000
print(arr2)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [39]:
arr1

array([  0,   2,   4, 500, 500])

In [40]:
# Some conditions very useful in Exploratory Data Analysis

val = 2

arr1 < 2

array([ True, False, False, False, False])

In [41]:
arr * 2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22]])

In [42]:
arr / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [1. , 1.5, 2. , 2.5, 3. ],
       [3.5, 4. , 4.5, 5. , 5.5]])

In [43]:
arr1[arr1<300]

array([0, 2, 4])

In [ ]:
# Create arrays and reshape

np.arrange(0,10)